#!/bin/bash
#
# This file is part of sysprep.
#
# sysprep is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# sysprep is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# sysprep. If not, see <https://www.gnu.org/licenses/>. 
#
# Copyright 2023 Jeremy Brubaker <jbrubake@orionarts.dev>
#
# abstract: tar(1) wrapper to allow Packer to archive an LXC image
#
# Hack around packer-plugin-lxc Issue #5
#     (https://github.com/hashicorp/packer-plugin-lxc/issues/5)
# Source: https://github.com/hashicorp/packer-plugin-lxc/issues/5#issuecomment-927375007
#
if [[ "${@: -1}" == "./rootfs" ]]; then
    # Override params to drop rootfs
    set -- "${@:1:1}" "$2/rootfs" "${@:3:2}" "--exclude=./dev/log" "${@:6:$(($# - 5 - 1 ))}" "."

    printf "Running tar in lxc namespace: '%s'\n" "$@"

    # Extract the image name
    t=${2%/*}
    name=${t##*/}

    # Run the original command in uid/gid mapped enviroment - root mapped uid
    # must have write permission in output director
    perms=$(lxc-info -c lxc.idmap $name | sed 's/lxc.idmap = //' |
        awk '{printf "-m %s:%s:%s:%s ", $1, $2, $3, $4}')
    lxc-usernsexec $perms -- command -p tar $@
else
    # Handles regular tar(1) usage
    command -p tar $@
fi

