#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2023 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: tar(1) wrapper to allow Packer to archive an LXC image
#
# Hack around packer-plugin-lxc Issue #5
#     (https://github.com/hashicorp/packer-plugin-lxc/issues/5)
# Source: https://github.com/hashicorp/packer-plugin-lxc/issues/5#issuecomment-2532841786
#
case ${@: -1} in
    # Export packer LXC images
    ./rootfs)
        # Override params to drop rootfs
        set -- "$1" "$2/rootfs" "$3" "--exclude=./dev/log" "${@:6:$(($# - 5 - 1 ))}" "."

        # Extract the image name
        t=${2%/*}
        name=${t##*/}

        # Run the original command in uid/gid mapped enviroment - root mapped uid
        # must have write permission in output director
        perms=$(lxc-info -c lxc.idmap $name | sed 's/lxc.idmap = //' | awk '{printf "-m %s:%s:%s:%s ", $1, $2, $3, $4}')
        lxc-usernsexec $perms -- command -p tar "$@"
        ;;

    # Required for the initial tar'ing of Ubuntu-24 Packer LXC images
    /*/rootfs) command -p tar "$@" --exclude=./var/log/journal ;;

    # Handles regular tar(1) usage
    *) command -p tar "$@" ;;
esac

